spring.application.name=social-graph-service
server.port=8082
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=harini2005
spring.data.neo4j.database=online-blog